// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentication.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetTokenInfoRequest is passed when dispatching
type GetTokenInfoRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenInfoRequest) Reset()         { *m = GetTokenInfoRequest{} }
func (m *GetTokenInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenInfoRequest) ProtoMessage()    {}
func (*GetTokenInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{0}
}

func (m *GetTokenInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenInfoRequest.Unmarshal(m, b)
}
func (m *GetTokenInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenInfoRequest.Merge(m, src)
}
func (m *GetTokenInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenInfoRequest.Size(m)
}
func (m *GetTokenInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenInfoRequest proto.InternalMessageInfo

func (m *GetTokenInfoRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// GetTokenInfoResponse return auth token information after successful verification
type GetTokenInfoResponse struct {
	ExpiresIn            int64    `protobuf:"varint,1,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenInfoResponse) Reset()         { *m = GetTokenInfoResponse{} }
func (m *GetTokenInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenInfoResponse) ProtoMessage()    {}
func (*GetTokenInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{1}
}

func (m *GetTokenInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenInfoResponse.Unmarshal(m, b)
}
func (m *GetTokenInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenInfoResponse.Merge(m, src)
}
func (m *GetTokenInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenInfoResponse.Size(m)
}
func (m *GetTokenInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenInfoResponse proto.InternalMessageInfo

func (m *GetTokenInfoResponse) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *GetTokenInfoResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GetTokenInfoResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTokenInfoRequest)(nil), "proto.GetTokenInfoRequest")
	proto.RegisterType((*GetTokenInfoResponse)(nil), "proto.GetTokenInfoResponse")
}

func init() {
	proto.RegisterFile("authentication.proto", fileDescriptor_d0dbc99083440df2)
}

var fileDescriptor_d0dbc99083440df2 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xc1, 0x4a, 0x03, 0x31,
	0x14, 0x64, 0x2d, 0x2d, 0xee, 0xc3, 0x53, 0x5c, 0x65, 0x59, 0x3d, 0x48, 0x4f, 0x8a, 0x90, 0x83,
	0x7e, 0x81, 0xbd, 0x94, 0xdc, 0xca, 0xea, 0x07, 0x98, 0xa6, 0xcf, 0x36, 0xb8, 0xe4, 0xc5, 0xe4,
	0xad, 0xf8, 0xf9, 0x92, 0x44, 0xd4, 0xc2, 0x9e, 0xc2, 0xcc, 0x64, 0x26, 0x33, 0x81, 0x46, 0x8f,
	0x7c, 0x40, 0xc7, 0xd6, 0x68, 0xb6, 0xe4, 0xa4, 0x0f, 0xc4, 0x24, 0xe6, 0xf9, 0x58, 0xde, 0xc3,
	0xf9, 0x1a, 0xf9, 0x85, 0xde, 0xd1, 0x29, 0xf7, 0x46, 0x3d, 0x7e, 0x8c, 0x18, 0x59, 0x34, 0x30,
	0xe7, 0xc4, 0xb5, 0xd5, 0x4d, 0x75, 0x5b, 0xf7, 0x05, 0x2c, 0x0f, 0xd0, 0x1c, 0x5f, 0x8e, 0x9e,
	0x5c, 0x44, 0x71, 0x0d, 0x35, 0x7e, 0x79, 0x1b, 0x30, 0xaa, 0xe2, 0x98, 0xf5, 0x7f, 0x84, 0xe8,
	0xe0, 0xd4, 0x0c, 0x16, 0x1d, 0xab, 0x5d, 0x7b, 0x92, 0xe3, 0x7e, 0xb1, 0xb8, 0x84, 0xc5, 0x18,
	0x31, 0xa8, 0x5d, 0x3b, 0xcb, 0xca, 0x0f, 0x7a, 0x78, 0x85, 0x8b, 0xa7, 0xa3, 0xd6, 0xcf, 0x18,
	0x3e, 0xad, 0x41, 0xb1, 0x86, 0xb3, 0xff, 0x15, 0x44, 0x57, 0xe6, 0xc8, 0x89, 0x11, 0xdd, 0xd5,
	0xa4, 0x56, 0x3a, 0xaf, 0xee, 0xa0, 0xdb, 0x93, 0xf6, 0x76, 0x4b, 0x76, 0xc0, 0xe0, 0x07, 0xcd,
	0x28, 0xf7, 0xc1, 0x1b, 0x99, 0x7e, 0x6b, 0x55, 0xa7, 0xd7, 0x37, 0xc9, 0xbd, 0xa9, 0xb6, 0x8b,
	0x1c, 0xf3, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xac, 0x9f, 0x15, 0x8c, 0x49, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticationServiceClient is the client API for AuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationServiceClient interface {
	GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error)
}

type authenticationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationServiceClient(cc grpc.ClientConnInterface) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoResponse, error) {
	out := new(GetTokenInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthenticationService/GetTokenInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServiceServer is the server API for AuthenticationService service.
type AuthenticationServiceServer interface {
	GetTokenInfo(context.Context, *GetTokenInfoRequest) (*GetTokenInfoResponse, error)
}

// UnimplementedAuthenticationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServiceServer struct {
}

func (*UnimplementedAuthenticationServiceServer) GetTokenInfo(ctx context.Context, req *GetTokenInfoRequest) (*GetTokenInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenInfo not implemented")
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_GetTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthenticationService/GetTokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetTokenInfo(ctx, req.(*GetTokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTokenInfo",
			Handler:    _AuthenticationService_GetTokenInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authentication.proto",
}
