// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	DispatchCommandRequest
	DispatchCommandResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// DispatchCommandRequest is passed when dispatching
type DispatchCommandRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *DispatchCommandRequest) Reset()                    { *m = DispatchCommandRequest{} }
func (m *DispatchCommandRequest) String() string            { return proto1.CompactTextString(m) }
func (*DispatchCommandRequest) ProtoMessage()               {}
func (*DispatchCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DispatchCommandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DispatchCommandRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// DispatchCommandResponse is empty.
type DispatchCommandResponse struct {
}

func (m *DispatchCommandResponse) Reset()                    { *m = DispatchCommandResponse{} }
func (m *DispatchCommandResponse) String() string            { return proto1.CompactTextString(m) }
func (*DispatchCommandResponse) ProtoMessage()               {}
func (*DispatchCommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*DispatchCommandRequest)(nil), "proto.DispatchCommandRequest")
	proto1.RegisterType((*DispatchCommandResponse)(nil), "proto.DispatchCommandResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Domain service

type DomainClient interface {
	DispatchCommand(ctx context.Context, in *DispatchCommandRequest, opts ...grpc.CallOption) (*DispatchCommandResponse, error)
}

type domainClient struct {
	cc *grpc.ClientConn
}

func NewDomainClient(cc *grpc.ClientConn) DomainClient {
	return &domainClient{cc}
}

func (c *domainClient) DispatchCommand(ctx context.Context, in *DispatchCommandRequest, opts ...grpc.CallOption) (*DispatchCommandResponse, error) {
	out := new(DispatchCommandResponse)
	err := grpc.Invoke(ctx, "/proto.Domain/DispatchCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Domain service

type DomainServer interface {
	DispatchCommand(context.Context, *DispatchCommandRequest) (*DispatchCommandResponse, error)
}

func RegisterDomainServer(s *grpc.Server, srv DomainServer) {
	s.RegisterService(&_Domain_serviceDesc, srv)
}

func _Domain_DispatchCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainServer).DispatchCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Domain/DispatchCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainServer).DispatchCommand(ctx, req.(*DispatchCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Domain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Domain",
	HandlerType: (*DomainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchCommand",
			Handler:    _Domain_DispatchCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto1.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x6e, 0x5c, 0x62, 0x2e, 0x99,
	0xc5, 0x05, 0x89, 0x25, 0xc9, 0x19, 0xce, 0xf9, 0xb9, 0xb9, 0x89, 0x79, 0x29, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x04, 0x17, 0x7b, 0x41, 0x62, 0x65, 0x4e, 0x7e, 0x62, 0x8a,
	0x04, 0x93, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x8c, 0xab, 0x24, 0xc9, 0x25, 0x8e, 0x61, 0x4e, 0x71,
	0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x51, 0x14, 0x17, 0x9b, 0x4b, 0x7e, 0x6e, 0x62, 0x66, 0x9e, 0x50,
	0x00, 0x17, 0x3f, 0x9a, 0x22, 0x21, 0x59, 0x88, 0x73, 0xf4, 0xb0, 0x3b, 0x42, 0x4a, 0x0e, 0x97,
	0x34, 0xc4, 0x6c, 0x27, 0x19, 0x2e, 0xde, 0xcc, 0x7c, 0xbd, 0xf4, 0xa2, 0x82, 0x64, 0x88, 0x42,
	0x27, 0xce, 0xd0, 0xe2, 0xd4, 0xa2, 0x00, 0x10, 0x33, 0x80, 0x31, 0x89, 0x0d, 0x2c, 0x66, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0xde, 0x08, 0xdd, 0x78, 0xf8, 0x00, 0x00, 0x00,
}
