// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// DispatchCommandRequest is passed when dispatching
type DispatchCommandRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DispatchCommandRequest) Reset()         { *m = DispatchCommandRequest{} }
func (m *DispatchCommandRequest) String() string { return proto.CompactTextString(m) }
func (*DispatchCommandRequest) ProtoMessage()    {}
func (*DispatchCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_711175b16516cce9, []int{0}
}
func (m *DispatchCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DispatchCommandRequest.Unmarshal(m, b)
}
func (m *DispatchCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DispatchCommandRequest.Marshal(b, m, deterministic)
}
func (dst *DispatchCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DispatchCommandRequest.Merge(dst, src)
}
func (m *DispatchCommandRequest) XXX_Size() int {
	return xxx_messageInfo_DispatchCommandRequest.Size(m)
}
func (m *DispatchCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DispatchCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DispatchCommandRequest proto.InternalMessageInfo

func (m *DispatchCommandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DispatchCommandRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// User object
type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FacebookId           string   `protobuf:"bytes,3,opt,name=facebookId,proto3" json:"facebookId,omitempty"`
	GoogleId             string   `protobuf:"bytes,4,opt,name=googleId,proto3" json:"googleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_711175b16516cce9, []int{1}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFacebookId() string {
	if m != nil {
		return m.FacebookId
	}
	return ""
}

func (m *User) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

// GetUserRequest is a request data to read user
type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_711175b16516cce9, []int{2}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// ListUserRequest is a request data to read all user for a given page
type ListUserRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserRequest) Reset()         { *m = ListUserRequest{} }
func (m *ListUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserRequest) ProtoMessage()    {}
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_711175b16516cce9, []int{3}
}
func (m *ListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequest.Unmarshal(m, b)
}
func (m *ListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequest.Marshal(b, m, deterministic)
}
func (dst *ListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequest.Merge(dst, src)
}
func (m *ListUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserRequest.Size(m)
}
func (m *ListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequest proto.InternalMessageInfo

func (m *ListUserRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListUserRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// ListUserResponse list of all users
type ListUserResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserResponse) Reset()         { *m = ListUserResponse{} }
func (m *ListUserResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserResponse) ProtoMessage()    {}
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_711175b16516cce9, []int{4}
}
func (m *ListUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResponse.Unmarshal(m, b)
}
func (m *ListUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResponse.Marshal(b, m, deterministic)
}
func (dst *ListUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResponse.Merge(dst, src)
}
func (m *ListUserResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserResponse.Size(m)
}
func (m *ListUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResponse proto.InternalMessageInfo

func (m *ListUserResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUserResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*DispatchCommandRequest)(nil), "proto.DispatchCommandRequest")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*GetUserRequest)(nil), "proto.GetUserRequest")
	proto.RegisterType((*ListUserRequest)(nil), "proto.ListUserRequest")
	proto.RegisterType((*ListUserResponse)(nil), "proto.ListUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	DispatchCommand(ctx context.Context, in *DispatchCommandRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) DispatchCommand(ctx context.Context, in *DispatchCommandRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.UserService/DispatchCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	DispatchCommand(context.Context, *DispatchCommandRequest) (*empty.Empty, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	ListUsers(context.Context, *ListUserRequest) (*ListUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_DispatchCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DispatchCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/DispatchCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DispatchCommand(ctx, req.(*DispatchCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchCommand",
			Handler:    _UserService_DispatchCommand_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_711175b16516cce9) }

var fileDescriptor_user_711175b16516cce9 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x6f, 0xe2, 0x30,
	0x10, 0x55, 0x20, 0x59, 0x36, 0xc3, 0x2e, 0xac, 0x46, 0xbb, 0x6c, 0x94, 0x7e, 0x28, 0xcd, 0x89,
	0x4b, 0x83, 0x44, 0x8f, 0xed, 0x89, 0x7e, 0xa2, 0xf6, 0x80, 0x52, 0xf5, 0x07, 0x98, 0xc4, 0x04,
	0xab, 0x09, 0x4e, 0x63, 0x53, 0x89, 0xff, 0xd7, 0x1f, 0x56, 0xd9, 0x4e, 0x5a, 0xa0, 0x3d, 0x65,
	0xde, 0xbc, 0x97, 0xf1, 0x9b, 0x37, 0x00, 0x6b, 0x41, 0xab, 0xa8, 0xac, 0xb8, 0xe4, 0xe8, 0xe8,
	0x8f, 0x7f, 0x90, 0x71, 0x9e, 0xe5, 0x74, 0xa4, 0xd1, 0x7c, 0xbd, 0x18, 0xd1, 0xa2, 0x94, 0x1b,
	0xa3, 0x09, 0x6f, 0x60, 0x70, 0xc5, 0x44, 0x49, 0x64, 0xb2, 0xbc, 0xe4, 0x45, 0x41, 0x56, 0x69,
	0x4c, 0x5f, 0xd6, 0x54, 0x48, 0x44, 0xb0, 0x57, 0xa4, 0xa0, 0x9e, 0x15, 0x58, 0x43, 0x37, 0xd6,
	0x35, 0x7a, 0xd0, 0x29, 0xc9, 0x26, 0xe7, 0x24, 0xf5, 0x5a, 0x81, 0x35, 0xfc, 0x15, 0x37, 0x30,
	0x5c, 0x82, 0xfd, 0x24, 0x68, 0x85, 0x3d, 0x68, 0xb1, 0xb4, 0xfe, 0xa7, 0xc5, 0x52, 0xfc, 0x0b,
	0x0e, 0x2d, 0x08, 0xcb, 0xb5, 0xde, 0x8d, 0x0d, 0xc0, 0x63, 0x80, 0x05, 0x49, 0xe8, 0x9c, 0xf3,
	0xe7, 0x69, 0xea, 0xb5, 0x35, 0xb5, 0xd5, 0x41, 0x1f, 0x7e, 0x1a, 0xd3, 0xd3, 0xd4, 0xb3, 0x35,
	0xfb, 0x81, 0xc3, 0x00, 0x7a, 0xb7, 0x54, 0xaa, 0xc7, 0x1a, 0xa7, 0x7b, 0x6f, 0x86, 0xe7, 0xd0,
	0x7f, 0x60, 0x62, 0x47, 0x82, 0x60, 0x97, 0x24, 0x33, 0xcb, 0x38, 0xb1, 0xae, 0x95, 0xb5, 0x9c,
	0x15, 0x4c, 0x6a, 0x6b, 0x4e, 0x6c, 0x40, 0x78, 0x0f, 0x7f, 0x3e, 0x7f, 0x16, 0x25, 0x5f, 0x09,
	0x8a, 0x27, 0xe0, 0xa8, 0x58, 0x85, 0x67, 0x05, 0xed, 0x61, 0x77, 0xdc, 0x35, 0xd9, 0x45, 0x5a,
	0x63, 0x18, 0x35, 0x4c, 0x72, 0x49, 0xf2, 0x66, 0x98, 0x06, 0xe3, 0x37, 0x0b, 0xba, 0x4a, 0xf5,
	0x48, 0xab, 0x57, 0x96, 0x50, 0xbc, 0x83, 0xfe, 0x5e, 0xda, 0x78, 0x54, 0x0f, 0xfb, 0xfe, 0x0a,
	0xfe, 0x20, 0x32, 0x8b, 0x47, 0xcd, 0xf5, 0xa2, 0x6b, 0x75, 0x3d, 0x3c, 0x85, 0x4e, 0x9d, 0x02,
	0xfe, 0xab, 0x27, 0xec, 0xa6, 0xe2, 0x6f, 0xbb, 0xc4, 0x0b, 0x70, 0x9b, 0xad, 0x04, 0x0e, 0x6a,
	0x66, 0x2f, 0x24, 0xff, 0xff, 0x97, 0xbe, 0xd9, 0x7f, 0x72, 0x08, 0xbf, 0x19, 0x8f, 0xb2, 0xaa,
	0x4c, 0x8c, 0x62, 0xe2, 0x2a, 0x7a, 0xa6, 0xca, 0x99, 0x35, 0xff, 0xa1, 0x7b, 0x67, 0xef, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x74, 0x9a, 0x4f, 0x4e, 0x7b, 0x02, 0x00, 0x00,
}
