/*
Package log provides Logger
*/
package log

import (
	"context"
	"log"

	"github.com/vardius/golog"

	"github.com/vardius/go-api-boilerplate/pkg/metadata"
)

const (
	// Prefix text to prefix to each log entry generated by the Logger
	TraceIDPrefix = "TraceID: %s "
)

// Logger allow to create logger based on env setting
type Logger struct {
	golog.Logger
}

// New creates new logger based on environment
func New(env string) *Logger {
	l := golog.New()
	if env != "development" {
		l.SetVerbosity(golog.DefaultVerbosity &^ golog.Debug)
	}

	l.SetFlags(log.Ldate | log.Ltime | log.Lmicroseconds | log.LUTC)

	return &Logger{l}
}

func (l *Logger) Debug(ctx context.Context, format string, args ...interface{}) {
	traceId := getTraceIdFromContext(ctx)
	newArgs := append([]interface{}{traceId}, args...)

	l.Debug(ctx, TraceIDPrefix+format, newArgs...)
}

func (l *Logger) Info(ctx context.Context, format string, args ...interface{}) {
	traceId := getTraceIdFromContext(ctx)
	newArgs := append([]interface{}{traceId}, args...)

	l.Logger.Info(ctx, TraceIDPrefix+format, newArgs...)
}

func (l *Logger) Warning(ctx context.Context, format string, args ...interface{}) {
	traceId := getTraceIdFromContext(ctx)
	newArgs := append([]interface{}{traceId}, args...)

	l.Logger.Warning(ctx, TraceIDPrefix+format, newArgs...)
}

func (l *Logger) Error(ctx context.Context, format string, args ...interface{}) {
	traceId := getTraceIdFromContext(ctx)
	newArgs := append([]interface{}{traceId}, args...)

	l.Logger.Error(ctx, TraceIDPrefix+format, newArgs...)
}

func (l *Logger) Critical(ctx context.Context, format string, args ...interface{}) {
	traceId := getTraceIdFromContext(ctx)
	newArgs := append([]interface{}{traceId}, args...)

	l.Logger.Critical(ctx, TraceIDPrefix+format, newArgs...)
}

func getTraceIdFromContext(ctx context.Context) string {
	mtd, ok := metadata.FromContext(ctx)
	if ok {
		return mtd.TraceID
	}

	return ""
}
